language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python test.py
- coverage run test.py
after_success: bash <(curl -s https://codecov.io/bash)

addons:
  ssh_known_hosts: moon.scs.ryerson.ca

